<?php
declare(strict_types=1);

namespace MikkoTest\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class PaymentDates extends Command
{
    protected function configure()
    {
        $this->setName('payment-dates:generate')
            ->setDescription('Generates a .csv file containing the payment dates for the sales staff')
            ->addArgument(
                'filename',
                InputArgument::REQUIRED,
                'The file name of the outputted .csv file'
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}